### PR TITLE
0.2.5 h8f162c

### PR DESCRIPTION
**Pull request by mediocretech**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mediocretech** [comment]
@conda-forge-admin, please rerun bot

**Comment by jakirkham** [comment]
Reading the label in case it helps

**Comment by jakirkham** [comment]
Ah missed this is a user PR (not a bot PR). Adding `bot rerun` won't work on user PRs (only bot PRs)

**Comment by h-vetinari** [comment]
Superseded by #13

**Pull request closed without merging**
